### ISSUE TITLE
[8.0] tko_web_sessions_management README - apt-get install libgeoip-dev

### ISSUE THREAD

**Issue by lukebranch** [thinkopensolutions/tkobr-addons#10]
@cmsalmeida ,

In Ubuntu 14.04 i've noticed that libgeoip-dev is required in order to successfully pip install GeoIP. I'd like to recommend putting it in the README file.

On another note, are there any plans to extend this module with features like auto-selecting the customer's shipping country, or language based on their IP/Country?

For auto-selecting a shipping country, I think this would be a really useful feature to add. If there are no plans i'll look into building one myself.

Also, just a quick question, how can I get the module to show the user's country as shown in the screenshot here?:

https://cloud.githubusercontent.com/assets/13301885/10918553/3b014d4a-825e-11e5-844b-b49c1d66da3d.png

I'd love to be able to check the not-logged in user's country from my own custom modules, specifically to handle language selection and shipping country among other things.

Thanks again for building such a useful module!

**Comment by cmsalmeida** [comment]
Hi,

Thank you for your message.

We have GeoIP in a 14.04 without that module installed.
Can you give us more details on how you installed it?

About the feature for auto-selecting the customer's shipping country, it would be better to develop it in a separated new module. We can do it, but not for now, send us some information if you will do it.

Any help please send us an email.

Best regards,

**Comment by lukebranch** [comment]
@cmsalmeida ,

Thanks for your response and my apologies on keeping you waiting on a reply.

Regarding the module installation the error was thrown during installation in the Odoo debug logs and simply alerted me of the missing dependency.

I will definitely get in touch if/when I decide to develop this module based on your code.
