### ISSUE TITLE
Import Module Error

### ISSUE THREAD

**Issue by AbdelRahman-Elposhi** [thinkopensolutions/tkobr-addons#145]
When i go to import the module into my odoo online i have this error:
`Error while importing module 'security': u'depends' Error while importing module 'static': u'depends'`

**Comment by cmsalmeida** [comment]
Can you explain in detail what you try to do?

**Comment by yk2kus** [comment]
Are you installing module in .zip format? if Yes then unzip it into addons folder, then restart Odoo server.

**Comment by yk2kus** [comment]
@AbdelRahman-Elposhi I am closing this because of no reply. If the problem persists please let us know.
