### ISSUE TITLE
install on odoo 10 app not show up.

### ISSUE THREAD

**Issue by 360org** [thinkopensolutions/tkobr-addons#155]
Hello i have try to install but cannot ater install by app store it say cannot install, i have download install by manual way also the app not show up. plz help
also this app https://www.odoo.com/apps/modules/10.0/tko_project_task_type/ same error

**Comment by zimbora69** [comment]
Hello,

tko_project_task_type for #v10 is not maintained/migrated by ThinkOpen Solutions Brasil.

It belongs to stellaf, his repo: https://github.com/stellaf/tko_project_task_type_v10/tree/10.0

Which other module couldn't you install from tkobr-addons, what is it's related version?

**Comment by 360org** [comment]
i thought the same author? :) that is ok, but about your module. how can i install it?

**Comment by 360org** [comment]
i try to install this tko_mail_smtp_per_user but not successfull

**Comment by zimbora69** [comment]
What issues you encountered installing tko_mail_smtp_per_user @W360S?

**Comment by 360org** [comment]
i already download from appstore put in custom_addons => update view list but it couldn't show up
event clone from git same.

**Comment by yk2kus** [comment]
@W360S could you install the module?

**Comment by 360org** [comment]
Yeap, i have installed

**Comment by yk2kus** [comment]
Great, Closing the issue.
