### ISSUE TITLE
Logín problem after a login error

### ISSUE THREAD

**Issue by acysos** [thinkopensolutions/tkobr-addons#25]
Hello,

I have detected a bug. It's complicated that the user replicate it.

Login with one user with blocked multiple sessions in one navigator. Go to other navigator and login again with the same user, it show the error that can't login, don't refresh this login screen with the error message.

Close the first session. Try to login again in the navigator with the login screen with error, the error login message disappear but it return to the standard login page. Checking the session it appear like logged but this user only see the login screen. If you try to login again it show login error message.

I try to find the problem, but I don't find it.

Greetings,
Ignacio Ibeas - Acysos

**Comment by cmsalmeida** [comment]
Thanks for your contribution.
We will try to replicate this, and get back to you after...

**Comment by cmsalmeida** [comment]
Are you behind a proxy (eg: nginx or apache)?

**Comment by acysos** [comment]
Our server is behind a proxy apache, like you see in the other issue. But I have detected the bug in our development server that it hasn't any proxy. Connect directly with IP and port.

Greetings

**Comment by cmsalmeida** [comment]
I will test like you explained, will come back soon.
Sorry for the delay, but we where overwelmed with request, just about getting head up :package: 

Thanks any way for your contribution...

**Comment by garzadekoster** [comment]
Yes I m behind a proxy (nginx), ..... (But in earlier version... worked fine either behind or not)
