### ISSUE TITLE
Problem with IP Request with apache proxy

### ISSUE THREAD

**Issue by acysos** [thinkopensolutions/tkobr-addons#26]
Hello,

I have detected other problem. When you use Apache Proxy, always return 127.0.0.1. I have solved with this code. 

`ip = request.httprequest.headers.environ['REMOTE_ADDR']
        if ip == '127.0.0.1' or ip == 'localhost':
            ip = load(urlopen('https://api.ipify.org/?format=json'))['ip']`

`if geo_ip_resolver:
            ip_location = (str(geo_ip_resolver.country_name_by_addr(
                ip)) or "")`

I know that is because I use a proxy, do you want that I send a PR with this change?

Greetings

**Comment by acysos** [comment]
This code not resolve the problem. Get the IP of the server. I have to investigate more.

Greetings

**Comment by acysos** [comment]
Now, with this code is solved:

`ip = request.httprequest.headers.environ['REMOTE_ADDR']
        if ip == '127.0.0.1' or ip == 'localhost':
            if request.httprequest.headers.environ['HTTP_X_FORWARDED_FOR']:
                ip = request.httprequest.headers.environ['HTTP_X_FORWARDED_FOR']`

Tell me, if you want that I send a PR.

Greetings

**Comment by cmsalmeida** [comment]
Thanks for you contribution.
Yes please, make a PR.
Greetings

**Comment by cmsalmeida** [comment]
Will you do the PR?

**Comment by cmsalmeida** [comment]
Sorry I did a PR, you can check it...

**Comment by cmsalmeida** [comment]
PR #100 merged, available both in 8.0 and 9.0.
Thank you for your colaboration.
:+1:
