### ISSUE TITLE
Programming error: relation "account_invoice_report" does not exist after 

### ISSUE THREAD

**Issue by whoople** [thinkopensolutions/tkobr-addons#5]
After making an update from module "tko_account_contract_report_template" in 'version': '0.046', to 'version': '0.050', on a server in version 8.0 commit 545cb3907a99b979a0d3428d3ad8edee1ccdecc5

Leads, contacts, Sales Team...  are not accesible at all without an error on screen : 

> > > >  ProgrammingError: relation "account_invoice_report" does not exist  <<<<

and this below error in logs :
Logs : --//
2015-09-07 19:50:10,661 2392 ERROR PROD openerp.sql_db: Programming error: relation "account_invoice_report" does not exist
LINE 11:                         FROM account_invoice_report account_...
                                      ^
, in query  WITH currency_rate (currency_id, rate, date_start, date_end) AS (
                                SELECT r.currency_id, r.rate, r.name AS date_start,
                                    (SELECT name FROM res_currency_rate r2
                                     WHERE r2.name > r.name AND
                                           r2.currency_id = r.currency_id
                                     ORDER BY r2.name ASC
                                     LIMIT 1) AS date_end
                                FROM res_currency_rate r
                                )
                      SELECT SUM(price_total \* cr.rate) as total
                        FROM account_invoice_report account_invoice_report, currency_rate cr
                       WHERE (("account_invoice_report"."partner_id" in (%s,%s))  AND  (("account_invoice_report"."state" not in (%s,%s)) OR "account_invoice_report"."state" IS NULL))
                         AND cr.currency_id = %s
                         AND (COALESCE(account_invoice_report.date, NOW()) >= cr.date_start)
                         AND (COALESCE(account_invoice_report.date, NOW()) < cr.date_end OR cr.date_end IS NULL)
//...

Thanks for your help..

**Comment by cmsalmeida** [comment]
Can you send this bug report to sac@tkobr.com.
Please add as much information as possible.
We will do as best as possible to check this with you.
Thanks!
