### ISSUE TITLE
Self signed up user lost access to front web shop access after they logged in

### ISSUE THREAD

**Issue by skygunner** [thinkopensolutions/tkobr-addons#57]
Hi,

After installed this module, all self signed up user lost access to front web shop access rights after they logged in, shows 403 after login. 

From the log: Only
Human Resources/Employee\n\t- Administration/Access Rights groups has the rights to access the shop.

Is there a config need to be done after the installation to restore the normal access rights?

Thanks.

**Comment by cmsalmeida** [comment]
I'm sorry, what was the module you installed?
The web sessions?
There is no after configurations to keep like it was.
But to start filtering and blocking then you need to configure groups and users.
Hope to help...
