### ISSUE TITLE
Error in install on odoo V10 Enterprise

### ISSUE THREAD

**Issue by ericzen** [thinkopensolutions/tkobr-addons#635]
Hello,

When i want to import this module on odoo Enterprise V10, i've this error :

Error while importing module 'tko_web_sessions_management': u"Impossible de charger le module tko_web_sessions_management \xe9chec : fichier /tmp/tmpyc0sbe/tko_web_sessions_management/security/ir.model.access.csv :\nAucun enregistrement trouv\xe9 pour id externe 'model_ir_sessions' dans le champ 'Object'\nERREUR: une valeur NULL viole la contrainte NOT NULL de la colonne \xab model_id \xbb\nD\xc9TAIL : La ligne en \xe9chec contient (754, null, t, access_ir_sessions, 1, 1, t, 2017-09-29 13:38:53.794477, f, t, 2017-09-29 13:38:53.794477, t, null)\n\nAucun enregistrement trouv\xe9 pour id externe 'model_ir_sessions' dans le champ 'Object'\nERREUR: une valeur NULL viole la contrainte NOT NULL de la colonne \xab model_id \xbb\nD\xc9TAIL : La ligne en \xe9chec contient (757, null, t, access_ir_sessions_erp_manager, 1, 1, t, 2017-09-29 13:38:53.794477, t, t, 2017-09-29 13:38:53.794477, t, 2)\n"

Some help will be great

Regards

**Comment by ericzen** [comment]
OK, After transfert of your module in addons folder and restat odoo service, i've installed the module.

But now i've an Error 500 page in login screen. 

If i see the logs the problem is due to login_success error.

 File "/usr/lib/python2.7/dist-packages/odoo/addons/website/controllers/main.py", line 84, in web_login
    if not redirect and request.params['login_success']:
KeyError: 'login_success'

What's the solution ?

Regards

**Comment by Tarekdh** [comment]
I have the same problem 
What's the solution ?

**Comment by lonelyleaves** [comment]
me too!
but can't solution!

**Comment by yk2kus** [comment]
We don't use enterprise edition. Closing this issue.
